type ChatBody={message?:string;role?:string;points?:number;history?:string[]};
const programContext=`You are Mentor Command, the friendly AI inside Mentor Match, a Per Scholas and CGI talent-bridge prototype. You are a general-purpose conversational assistant and must carry context forward naturally. Respond naturally to greetings, small talk, everyday questions, and current-information questions. Do not force every answer back to careers. If someone asks for interview preparation without naming a role, ask what role. When their next message names a role such as cybersecurity or software engineering, immediately provide at least six numbered interview questions, each followed by a useful sample answer. For meeting agendas, action points, tasks, opportunities, and career plans, use a conversational question-and-answer format with at least six numbered pairs whenever the user asks for details. Remember which topic and numbered item the user is discussing so follow-ups like “tell me more about number two” make sense. When the user asks about Mentor Match, use this program knowledge: students earn points through mentoring sessions, resume updates, workshops, mock interviews, GitHub projects, networking, peer support, and feedback. Mentors earn points through goal-setting sessions, reviews, mock interviews, opportunity sharing, workshops, introductions, and check-ins. Rewards include career reviews, conferences, leadership sessions, certification support, job shadowing, innovation labs, and priority interview consideration when qualified. Never promise a job or guaranteed interview. When career help is requested, be practical, encouraging, and specific. End longer coaching answers with one conversational next step.`;
const weatherDescriptions:Record<number,string>={0:"clear skies",1:"mostly clear skies",2:"partly cloudy skies",3:"overcast skies",45:"fog",48:"freezing fog",51:"light drizzle",53:"drizzle",55:"heavy drizzle",61:"light rain",63:"rain",65:"heavy rain",71:"light snow",73:"snow",75:"heavy snow",80:"light rain showers",81:"rain showers",82:"heavy rain showers",95:"thunderstorms",96:"thunderstorms with hail",99:"strong thunderstorms with hail"};
async function atlantaWeather(){const url="https://api.open-meteo.com/v1/forecast?latitude=33.749&longitude=-84.388&current=temperature_2m,apparent_temperature,relative_humidity_2m,precipitation,weather_code,wind_speed_10m&temperature_unit=fahrenheit&wind_speed_unit=mph&timezone=America%2FNew_York";const response=await fetch(url,{headers:{Accept:"application/json"}});if(!response.ok)throw new Error("weather unavailable");const data=await response.json() as {current?:{temperature_2m?:number;apparent_temperature?:number;relative_humidity_2m?:number;weather_code?:number;wind_speed_10m?:number}};const w=data.current;if(!w)throw new Error("weather unavailable");const condition=weatherDescriptions[w.weather_code??-1]||"mixed conditions";return `Right now in Atlanta, it’s ${Math.round(w.temperature_2m??0)}°F with ${condition}. It feels like ${Math.round(w.apparent_temperature??w.temperature_2m??0)}°F, humidity is ${Math.round(w.relative_humidity_2m??0)}%, and winds are around ${Math.round(w.wind_speed_10m??0)} mph. Want the forecast too?`;}
const cyberInterview=`Absolutely—let’s prepare you for a cybersecurity interview. Here are six strong questions and sample answers:

1. What is the difference between a threat, vulnerability, and risk?
Sample answer: A threat is something that could cause harm, a vulnerability is a weakness that could be exploited, and risk is the likelihood and impact of that threat exploiting the vulnerability.

2. How would you respond to a suspected phishing attack?
Sample answer: I would isolate affected accounts or devices, preserve evidence, review email headers and logs, reset compromised credentials, block malicious indicators, notify the incident-response team, and document lessons learned.

3. What is the principle of least privilege?
Sample answer: Users and systems should receive only the access needed to perform their duties. This limits the damage caused by compromised accounts and reduces accidental misuse.

4. What is the CIA triad?
Sample answer: Confidentiality protects data from unauthorized access, integrity protects it from improper changes, and availability ensures authorized users can access it when needed.

5. How do you prioritize vulnerabilities?
Sample answer: I consider severity, exploitability, whether the asset is internet-facing, business importance, existing controls, and active exploitation—not just the CVSS score.

6. Tell me about a security incident you handled.
Sample answer: I would use STAR: explain the situation, my responsibility, the containment and investigation steps I took, and the measurable result or process improvement.

Want me to interview you one question at a time and coach your answers?`;
const softwareInterview=`Perfect—let’s prepare you for a software-engineering interview. Here are six realistic questions and sample answers:

1. Tell me about a project you built.
Sample answer: I helped build an AI career platform with React and Vite. I focused on the user interface and flow, created reusable components, and helped migrate the front end to TypeScript for maintainability and fewer bugs.

2. What is the difference between state and props in React?
Sample answer: Props are values passed into a component by its parent. State is data managed inside the component that can change over time and trigger a re-render.

3. How do you debug a problem?
Sample answer: I reproduce the issue, narrow down the failing layer, inspect logs and inputs, form a hypothesis, test one change at a time, and add a test so the problem does not return.

4. What is an API?
Sample answer: An API is a defined way for systems to communicate. A front end might send an HTTP request to a back end, which validates it, works with data, and returns a structured response such as JSON.

5. How do you work on a development team?
Sample answer: I clarify requirements, break work into manageable tasks, communicate blockers early, use version control, review code respectfully, and keep the user’s needs at the center.

6. Why should we hire you?
Sample answer: I combine software training with 11 years of customer service and technical support. I can understand the user’s problem, explain technical ideas clearly, and help build practical solutions.

Want to practice these one at a time, starting with your project story?`;
function fallback(message:string,role:string,points:number,history:string[]){const q=message.toLowerCase().trim();const prior=history.slice(-6).join(" ").toLowerCase();
 if(/^(hi|hello|hey|yo|good (morning|afternoon|evening))[!. ]*$/.test(q))return "Hey! How are you doing today? You can talk with me normally or ask me for help with careers, Mentor Match, interviews, tech, or whatever’s on your mind.";
 if(/how are you|how'?s it going|what'?s up/.test(q))return "I’m doing well—and I’m glad you stopped by. How are you doing?";
 if(/thank|thanks/.test(q))return "You’re welcome! What else can I help you with?";
 if(/what (day|date)|today'?s date/.test(q))return `Today is ${new Intl.DateTimeFormat("en-US",{weekday:"long",month:"long",day:"numeric",year:"numeric",timeZone:"America/New_York"}).format(new Date())}.`;
 if(/\brag\b|retrieval.?augmented|what kind of agent|how (do you|does this) work/.test(q))return "I’m a hybrid conversational career agent—not a full document RAG agent yet. I remember this conversation, use verified Mentor Match program context, run structured coaching workflows, and can use OpenAI with live web search when connected. True RAG would add document uploads, chunking, embeddings, a vector database, source retrieval, and citations. This prototype is RAG-ready, and that document layer is the next upgrade.";
 if(/not sure|don't know|dont know|what should i do/.test(q))return role==="Mentor"?"We can figure it out together. If you mean Mentor Match, reviewing a student portfolio or scheduling a mock interview would be a strong next move. Or tell me what’s on your mind and we’ll start there.":"We can figure it out together. If you mean your career, a mock interview or a small GitHub project would be a strong next move. Or tell me what’s on your mind and we’ll start there.";
 if(/why|explain/.test(q)&&prior)return "Good question. Tell me which part felt unclear, and I’ll explain it in plain language with an example.";
 if((/cyber.?security|security analyst|soc analyst/.test(q))&&(/interview|role are you targeting|prepare|practice/.test(prior+" "+q)))return cyberInterview;
 if((/software|developer|engineer|front.?end|back.?end|full.?stack/.test(q))&&(/interview|role are you targeting|prepare|practice/.test(prior+" "+q)))return softwareInterview;
 if(/meeting agenda|first meeting|agenda/.test(q))return role==="Mentor"?`Absolutely. Here are six conversational questions and suggested answers for your first mentor meeting:\n\n1. Question: “Tell me about yourself and what you want from mentoring.”\nSuggested answer: “I’d like to understand your goals, share relevant experience, and help you leave each meeting with a practical next step.”\n\n2. Question: “What role are you working toward?”\nSuggested answer: Listen for the specific job, timeline, and reason it interests the student, then restate the goal to confirm it.\n\n3. Question: “What strengths can we build on?”\nSuggested answer: Identify two proven strengths from their work history, training, or portfolio.\n\n4. Question: “What is your biggest obstacle right now?”\nSuggested answer: Agree on one priority instead of trying to solve everything in the first meeting.\n\n5. Question: “What can we accomplish in the next 30 days?”\nSuggested answer: Choose two measurable actions with deadlines and clear ownership.\n\n6. Question: “When should we meet again?”\nSuggested answer: Schedule the follow-up and agree on how progress updates will be shared.\n\nWhich question would you like me to help you practice?`:`Absolutely. Here are six conversational questions and sample answers for your first mentor meeting:\n\n1. Question: “Tell me about yourself.”\nSample answer: “I have a background in customer service and technical support, completed software-engineering training through Per Scholas, and I’m now working toward a technology or consulting role.”\n\n2. Question: “What career are you targeting?”\nSample answer: “I’m targeting software engineering, cybersecurity, or technology consulting where I can combine technical problem-solving with customer experience.”\n\n3. Question: “What are your strongest skills?”\nSample answer: “My strengths are troubleshooting, communicating technical ideas clearly, understanding user needs, and building clean front-end experiences.”\n\n4. Question: “Where do you need the most help?”\nSample answer: “I want help strengthening my technical interview answers, presenting my projects, and identifying the right opportunities.”\n\n5. Question: “What is one 30-day goal?”\nSample answer: “I will polish one GitHub project, complete two mock interviews, and tailor my résumé for my target role.”\n\n6. Question: “How can I support you between meetings?”\nSample answer: “Accountability, honest feedback, and introductions to people who understand the field would help me most.”\n\nWould you like to practice these one at a time?`;
 if(/point|earn|task|my tasks|action point/.test(q))return role==="Mentor"?`You have ${points.toLocaleString()} mentor points. Let’s turn the program into six clear questions and answers:\n\n1. Question: “What is my quickest action?”\nAnswer: Share a verified industry opportunity for 75 points.\n\n2. Question: “How can I directly help a student?”\nAnswer: Review a résumé for 100 points or complete a goal-setting session for 150 points.\n\n3. Question: “What interview action can I take?”\nAnswer: Host a consulting mock interview for 200 points.\n\n4. Question: “What is the highest-value action?”\nAnswer: Lead a technical workshop for 300 points.\n\n5. Question: “Can networking earn points?”\nAnswer: Yes. Introduce a mentee to a relevant colleague for 175 points.\n\n6. Question: “How are points verified?”\nAnswer: Log the activity, include the date and participant, and submit any requested confirmation.\n\nWhich action do you want to start?`:`You have ${points.toLocaleString()} student points. Here are six conversational questions and answers about your next actions:\n\n1. Question: “What is my quickest task?”\nAnswer: Complete the mentor feedback survey for 50 points.\n\n2. Question: “What task earns the most points?”\nAnswer: Publish a GitHub portfolio project for 250 points.\n\n3. Question: “How can I prepare for interviews?”\nAnswer: Complete a mock interview for 200 points and review the feedback with your mentor.\n\n4. Question: “Can improving my résumé earn points?”\nAnswer: Yes. Upload a revised technical résumé for 100 points.\n\n5. Question: “Does networking count?”\nAnswer: Yes. Attend an approved networking event for 125 points.\n\n6. Question: “What should I do first?”\nAnswer: Start with the task that supports your immediate career goal, then choose a quick task to build momentum.\n\nTell me your target role and I’ll recommend the best first action.`;
 if(/match|mentor|mentee/.test(q))return role==="Student"?"I’d match you using goals, industry interest, availability, and communication style—not just job title. What skill do you most want help improving?":"I’d match you with students whose goals align with your expertise and availability. Do you prefer technical coaching, career guidance, or interview preparation?";
 if(/interview|hired|job search|career/.test(q))return "Absolutely—I can prepare you with realistic questions and strong sample answers, then quiz you one question at a time. What kind of role is the interview for: cybersecurity, software engineering, cloud, IT support, consulting, or something else?";
 if(/resume|linkedin|portfolio/.test(q))return "Absolutely. We’ll show the problem you solved, your personal contribution, the technology used, and a measurable result. Which are we improving: your resume, LinkedIn, or GitHub portfolio?";
 if(/conference|event|opportun|reward/.test(q))return `You have ${points.toLocaleString()} points. Here are six conversational questions and answers about available opportunities:\n\n1. Question: “Can I shadow a technology team?”\nAnswer: Yes. CGI Technology Shadow Day requires 750 points and lets participants observe a delivery team.\n\n2. Question: “Can someone review my portfolio?”\nAnswer: Yes. A Technical Portfolio Review costs 500 points and includes feedback from a senior engineer.\n\n3. Question: “Can I practice interviewing?”\nAnswer: Yes. The Consulting Mock Interview requires 1,000 points and includes written feedback.\n\n4. Question: “Can I attend an industry conference?”\nAnswer: Yes. The Cloud and AI Leadership Forum unlocks at 1,500 points.\n\n5. Question: “Can the program help with certifications?”\nAnswer: Yes. A Certification Voucher is available at 2,000 points for approved credentials.\n\n6. Question: “Can points help me get considered for a job?”\nAnswer: At 3,000 points, qualified participants can unlock Career Fast Track priority consideration. It does not guarantee an interview or job.\n\nWhich opportunity do you want to explore first?`;
 if(/aws|cloud/.test(q))return "AWS could host the application, store program records, run the backend, and power AI through Amazon Bedrock. Would you like the simple explanation or a full architecture plan?";
 return "I hear you. I can have a real conversation and help with a lot of everyday or career questions, but this demo’s free mode doesn’t know every topic yet. Ask me another way, or try weather, interview prep, resumes, AWS, Mentor Match, points, or opportunities.";}
export async function POST(request:Request){const{message="",role="Student",points=0,history=[]}=await request.json() as ChatBody;if(/\b(weather|temperature|forecast)\b/i.test(message)&&(!/\bin\s+[a-z]/i.test(message)||/atlanta|atl\b/i.test(message))){try{return Response.json({answer:await atlantaWeather(),mode:"LIVE ATLANTA WEATHER"})}catch{}}
 const apiKey=process.env.OPENAI_API_KEY;if(apiKey){try{const input=[...history.slice(-14).map(text=>({role:text.startsWith("You: ")?"user":"assistant",content:text.replace(/^You: /,"")})),{role:"user",content:message}];const response=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{Authorization:`Bearer ${apiKey}`,"Content-Type":"application/json"},body:JSON.stringify({model:process.env.OPENAI_MODEL||"gpt-5.6-luna",instructions:`${programContext}\nCurrent Mentor Match role: ${role}. Current points: ${points}.`,input,tools:[{type:"web_search"}],store:false,max_output_tokens:1000})});if(response.ok){const data=await response.json() as {output?:Array<{content?:Array<{type?:string;text?:string}>}>};const answer=data.output?.flatMap(x=>x.content||[]).find(x=>x.type==="output_text")?.text;if(answer)return Response.json({answer,mode:"OPEN AI + LIVE WEB"})}}catch{}}
 return Response.json({answer:fallback(message,role,points,history),mode:"SMART DEMO MODE"});}
